version: '3.5'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - bot_network
    env_file:
      - /root/enviroments/.env
    
volumes:
  postgres_data:

networks:
  bot_network:
    external: true
